### ISSUE TITLE
Failed opening required 'utils/Entitlement.php'

### ISSUE THREAD

**Issue by magnolia61** [sgladstone/com.fountaintribe.financialsummaries#1]
Hi Sarah,
I stumbled upon this extension and found a tiny bug I think:

Fatal error: require_once(): Failed opening required 'utils/Entitlement.php'
Could it be that file has now been renamed to: FinEntitlement.php?
:-)

**Comment by sgladstone** [comment]
This issue has been fixed in version 2.0.2
