### ISSUE TITLE
split() function deprecated PHP7

### ISSUE THREAD

**Issue by magnolia61** [sgladstone/com.fountaintribe.financialsummaries#2]
Hi Sarah,
Probably this is a php7 issue.
The manual says: Split() was DEPRECATED in PHP 5.3.0, and REMOVED in PHP 7.0.0. 

Error: Call to undefined function split() in FormattingUtils->get_date_formatted_short_form() (line 82 of /home/xyz/domains/ourdomain.nl/public_html/prod/sites/all/modules/civicrm_extensions/com.fountaintribe.financialsummaries/utils/FormattingUtils.php).

Thought you'd want to know :-)

**Comment by sgladstone** [comment]
This has been fixed in the latest version of this extension.
